### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by srflp** [KernelTuner/kernel_tuner#156]
Trying to use this library on Windows 11, Python 3.10, I receive:

```
Traceback (most recent call last):
  File "C:\Users\<...>\kernel_tuner\examples\cuda\matmul.py", line 10, in <module>
    import kernel_tuner
  File "C:\Users\<...>\kernel_tuner\kernel_tuner\__init__.py", line 4, in <module>
    from kernel_tuner.interface import tune_kernel, run_kernel
  File "C:\Users\<...>\kernel_tuner\kernel_tuner\interface.py", line 36, in <module>
    import kernel_tuner.core as core
  File "C:\Users\<...>\kernel_tuner\kernel_tuner\core.py", line 7, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

**Comment by benvanwerkhoven** [comment]
Hi @srflp, Thank you for reporting this issue! It seems the resource module sometimes doesn't exist on Windows. We actually don't rely on it that heavily. Resource was only used to report memory usage for logging debug information. I have just committed a fix to master. Please note that we don't test that often on Windows, so there may be other issues you run into. I would be happy to hear about those and fix them for you if you would be willing to report them however.

**Comment by benvanwerkhoven** [comment]
I believe this has been fixed, if not please feel free to reopen.
