### ISSUE TITLE
Error in expdist.py

### ISSUE THREAD

**Issue by isazi** [KernelTuner/kernel_tuner#192]
There is an error in comparing `RuntimeFailedConfig` with other values in the `expdist.py` example.

```
best performing configuration:
block_size_x=32, block_size_y=1, tile_size_x=8, tile_size_y=2, use_shared_mem=0, time=0.541ms
Traceback (most recent call last):
  File "/home/alessio/src/kernel_tuner/examples/cuda/expdist.py", line 65, in <module>
    tune_expdist()
  File "/home/alessio/src/kernel_tuner/examples/cuda/expdist.py", line 46, in tune_expdist
    best_config1 = min(kernel1[0], key=lambda x:x['time'])
TypeError: '>' not supported between instances of 'numpy.ndarray' and 'RuntimeFailedConfig'
```

**Comment by benvanwerkhoven** [comment]
Thanks for letting me know! It's fixed now!
